# This file is a template, and might need editing before it works on your project.
# Official docker image.
image: docker:latest

stages:
  - registry
  - deploy

services:
  - docker:dind

variables:
  DOMAIN_STAG_URL: ndtg.cf

before_script:
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

registry-master:
  stage: registry
  tags:
    - container-registry
  script:
    - docker build -f Dockerfile.prod --pull -t $CI_REGISTRY_IMAGE .
    - docker push $CI_REGISTRY_IMAGE
  only:
    - master

registry-version:
  stage: registry
  tags:
    - container-registry
  script:
    - docker build -f Dockerfile.stag --pull -t $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG .
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
  only:
    - /^v(\d+(\-\d+)*)+|develop$/

deploy-prod:
  stage: deploy
  tags:
    - deploy-prod
  script:
    - docker stack deploy -c ./docker-compose.prod.yml $CI_PROJECT_NAME-$CI_COMMIT_REF_SLUG
  only:
    - master

deploy-version:
  stage: deploy
  tags:
    - deploy-version
  script:
    - |
      if [ $CI_COMMIT_REF_SLUG == develop ]; then
        export URL_CI_COMMIT_REF_SLUG=
      else
        export URL_CI_COMMIT_REF_SLUG=$CI_COMMIT_REF_SLUG
      fi
    - docker stack deploy -c ./docker-compose.stag.yml $CI_PROJECT_NAME-$CI_COMMIT_REF_SLUG
  only:
    - /^v(\d+(\-\d+)*)+|develop$/
