version: '3'

services:
  app:
    image: php-traefik
    env_file: docker-compose.env
    volumes:
      - ~/PhpstormProjects/:/var/www/html/
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    labels:
      - traefik.port=80
      - traefik.enable=true
      - traefik.docker.network=traefik_proxy
      - traefik.frontend.entryPoints=https,http
      - traefik.frontend.rule=Host:php.local.dev;PathPrefix:/
    networks:
      - traefik

networks:
  traefik:
    external:
      name: traefik_proxy
