version: '3'

services:
  app:
    image: $CI_REGISTRY_IMAGE:latest
    env_file:
      - docker-compose.prod.env
    deploy:
      replicas: 4
      restart_policy:
        condition: on-failure
        max_attempts: 10
    labels:
      - traefik.port=80
      - traefik.enable=true
      - traefik.docker.network=traefik_proxy
      - traefik.frontend.entryPoints=https,http
      - traefik.frontend.rule=Host:$CI_PROJECT_NAME.$DOMAIN_PROD_URL;PathPrefix:/
    networks:
      - traefik

networks:
  traefik:
    external:
      name: traefik_proxy
